import type { Metadata } from 'next';
import './globals.css';
import Hero from '@/components/Hero';
import Footer from '@/components/Footer';
import { Quicksand } from 'next/font/google';

const quicksand = Quicksand({ subsets: ['latin'], weight: ['400', '700'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={quicksand.className}>
      <body className="mx-auto">
        <div className="px-20">
          <Hero />
          <main>{children}</main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
